import fs from 'node:fs';
import path from 'node:path';
import { Db } from './db.js';
import { dataDir } from './paths.js';
import { ensureDir } from './util.js';

type ExportFormat = 'jsonl' | 'csv' | 'duckdb-sql';

function csvEscape(value: unknown): string {
  const text = value == null ? '' : String(value);
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function exportRows(db: Db, since?: string) {
  const where = since ? 'WHERE started_at >= @since' : '';
  return db.prepare(`
SELECT
  id, source, external_id, project, provider, model, workflow, cwd,
  git_remote, git_branch, git_commit, started_at, ended_at, duration_ms,
  status, input_tokens, output_tokens, total_tokens, estimated_tokens,
  estimated_cost_usd, error
FROM runs
${where}
ORDER BY started_at
`).all(since ? { since } : {}) as Record<string, unknown>[];
}

export function exportAnalytics(db: Db, opts: { format?: ExportFormat; out?: string; since?: string } = {}) {
  const format = opts.format || 'jsonl';
  const dir = path.join(dataDir(), 'exports');
  ensureDir(dir);
  const out = opts.out || path.join(dir, `agentscope-runs-${new Date().toISOString().slice(0, 10)}.${format === 'duckdb-sql' ? 'sql' : format}`);
  ensureDir(path.dirname(out));

  if (format === 'duckdb-sql') {
    const csv = out.replace(/\.sql$/, '.csv');
    exportAnalytics(db, { format: 'csv', out: csv, since: opts.since });
    const sql = [
      '-- DuckDB import script generated by AgentScope',
      `CREATE OR REPLACE TABLE agentscope_runs AS SELECT * FROM read_csv_auto('${csv.replace(/'/g, "''")}');`,
      'SELECT project, provider, model, COUNT(*) runs, SUM(total_tokens) tokens, SUM(estimated_cost_usd) cost',
      'FROM agentscope_runs GROUP BY project, provider, model ORDER BY tokens DESC;',
      '',
    ].join('\n');
    fs.writeFileSync(out, sql);
    return { format, file: out, companionCsv: csv };
  }

  const rows = exportRows(db, opts.since);
  if (format === 'jsonl') {
    fs.writeFileSync(out, rows.map((row) => JSON.stringify(row)).join('\n') + (rows.length ? '\n' : ''));
  } else if (format === 'csv') {
    const headers = rows[0] ? Object.keys(rows[0]) : ['id', 'source', 'project', 'provider', 'model', 'started_at', 'total_tokens', 'estimated_cost_usd'];
    const lines = [headers.join(','), ...rows.map((row) => headers.map((h) => csvEscape(row[h])).join(','))];
    fs.writeFileSync(out, lines.join('\n') + '\n');
  } else {
    throw new Error(`Unsupported analytics export format: ${format}`);
  }
  return { format, file: out, rows: rows.length };
}
